server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    # Como é uma SPA, rotas como /login ou /feed precisam cair no index.html.
    try_files $uri $uri/ /index.html;
  }
}
